import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from "sonner";


const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: "STUD-AI AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme: "dark"
    }}>
      <html lang="en" className="dark" suppressHydrationWarning>
        <body
          className={`${inter.className}`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* Header */}
            <Header />
            {/* Main */}
            <main className="min-h-screen">{children}</main>
            <Toaster richColors/>
            {/* Footer */}
            <footer className="bg-muted/50 py-12 ">
              <div className="container mx-auto text-center text-gray-200">
                <p>Made with 💗 by Rushikesh</p>
              </div>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
